


#remotes::install_github("bcgov/PEMprepr", build_vignettes = TRUE)
devtools::load_all("D:\\PEM_DATA\\PEMprepr")
devtools::load_all("D:\\PEM_DATA\\PEMsamplr")

library(PEMprepr)
library(PEMsamplr)
library(ggplot2)
library(sf)
library(terra)


fid <- setup_folders("DateCreek_AOI")

# location of the transect layout (sample plan)
trans_input <- fid$sampleplan_final_transect[2]
trans_output <- fid$trainpts_201040[2]

# location of the raw field data
rawdat <- fid$trainpts_transect[2]

# output location for cleaned data
cleandat <- fid$trainpts_maps[2]
# Create a consolidated transect layout


# consolidate transect data

transect_layout <- generate_transectlayout(trans_input)

transect_layout_buf <- sf::st_buffer(transect_layout, 10)

st_write(transect_layout, file.path(trans_output, "transect_layout_s1.gpkg"), delete_layer = TRUE)



# import and clean field data

points <- format_fielddata(rawdat, transect_layout_buf)

sf::st_write(points, file.path(cleandat, "s1_points.gpkg"), delete_layer = TRUE)


# format tracklog

tracks <- format_tracklog(rawdat, transect_layout_buf)

sf::st_write(tracks, file.path(cleandat, "s1_tracklog.gpkg"), delete_layer = TRUE)


# covert to lines
processed_transects <- make_lines(GPSPoints = points,
                                  Transects = transect_layout_buf,
                                  method = "pts2lines",
                                  tBuffer = 20, PROJ = 3005) %>%
  dplyr::select(-TID, -ID)

#st_write(processed_transects,  file.path(cleandat, "proc_s1_transects.gpkg"),
#         delete_layer = TRUE)

st_write(processed_transects,  file.path(cleandat, "proc_s1_transects.gpkg"),
         delete_layer = TRUE)


# Create a Summary of the training point data

trainingpt_report(tpts = points, trans = processed_transects, out_dir = cleandat)










# attribute and add neighbours to the training data



## clean points
cleandat <- fid$trainpts_maps[2]

res_folder = "5m"

#location of raster base on which modelling will be applied
covdir <- fid$cov_dir_1020[2]

# location of attributed and output data
outdat <- fid$training_data_1030[2]


# read in the raster template used for modelling (i.e 5m resolution)
trast <- terra::rast(file.path(covdir, res_folder,"template.tif"))

#tpoints <- st_read(file.path(cleandat, "s2_points.gpkg"))

processed_transects <- st_read(file.path(cleandat, "proc_s1_transects.gpkg"))

if("ID" %in% colnames(processed_transects) == FALSE){
  print ("adding ID column")
  processed_transects <- processed_transects %>%
    mutate(ID = seq(1, length(processed_transects$order), 1))
}

processed_transects_id <- st_drop_geometry(processed_transects)

# transv <- terra::vect(file.path(cleandat, "proc_s1_transects_datecreek.gpkg"))

lBuff <- processed_transects %>%
  sf::st_buffer(., dist = 2.5, endCapStyle = "FLAT", joinStyle = "MITRE") %>%
  sf::st_cast(.,"MULTIPOLYGON")

# convert to spatVect
transv <- terra::vect(lBuff )

# extract the XY values of raster cells where crossed lines
xys <- terra::extract(trast,transv, xy = TRUE )

# add the additional points back to full dataset
raster_points_xy <- xys %>%
  st_as_sf(coords = c("x", "y"), crs = 3005) %>%
  merge(processed_transects_id) %>%
  select(-ID, -template)

# add slice and tid (transect id)

allpts <-raster_points_xy %>%
  mutate(tid = tolower(gsub("_[[:alpha:]].*","", transect_id))) %>%
  mutate(slice = sub('.*(?=.$)', '',gsub("\\..*","", tid), perl=T))



## Addd neighbours
tpoints_ne <- add_neighbours(allpts,trast)

head(tpoints_ne)

allrasts <- file.path(covdir, res_folder)

#cov_dir = allrasts

allpts <- attribute_points(tpoints_ne, allrasts)

st_write(allpts, dsn = file.path(fid$training_data_1030[2], "allpts.gpkg"), delete_layer = TRUE)

